---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnopresources.nop.example.org
spec:
  compositeTypeRef:
    apiVersion: nop.example.org/v1alpha1
    kind: XNopResource
  mode: Pipeline
  pipeline:
  - step: conditional-patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
         - name: test-resource
           base:
            apiVersion: nop.crossplane.io/v1alpha1
            kind: NopResource
            metadata:
              labels:
                security-setting: "true"
            spec:
              forProvider:
                fields:
                  integerField: 42
                  stringField: "string"
                  objectField:
                    stringField: "object"
                  arrayField:
                  - stringField: "array"
                conditionAfter:
                - time: 5s
                  conditionType: Ready
                  conditionStatus: "True"
                connectionDetails:
                - name: username
                  value: fakeuser
                - name: password
                  value: verysecurepassword
                - name: endpoint
                  value: 127.0.0.1
         - name: bad-resource
           base:
            apiVersion: nop.crossplane.io/v1alpha1
            kind: NopResource
            metadata:
              labels:
                security-setting: "true"
            spec:
              forProvider:
                fields:
                  integerField: 42
                  stringField: "string"
                  objectField:
                    stringField: "object"
                  arrayField:
                  - stringField: "array"
                conditionAfter:
                - time: 5s
                  conditionType: Ready
                  conditionStatus: "True"
                connectionDetails:
                - name: username
                  value: fakeuser
                - name: password
                  value: verysecurepassword
                - name: endpoint
                  value: 127.0.0.1
  - step:
    functionRef:
      name: function-unit-test
    input:
      apiVersion: unittest.fn.crossplane.io/v1beta1
      kind: TestCases
      errorOnFailedTest: false
      testCases:
      - description: "test pass"
        assert: observed.composite.resource.spec.env == "dev"
      - description: "test fail"
        assert: observed.composite.resource.spec.env == "prod"
      # - description: "test error"
      #   assert: a == b
      - assert: |-
          "kind" in desired.resources['test-resource'].resource &&
          desired.resources['test-resource'].resource.kind == 'NopResource'
        description: all resources "test" is of "NopResource" kind
      - assert: |- 
          desired.resources.all(r, "labels" in desired.resources[r].resource.metadata && 
          "security-setting" in desired.resources[r].resource.metadata.labels &&
          desired.resources[r].resource.metadata.labels["security-setting"] == "true")
        description: All resources have the "security-setting" label


